# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 11abf97fc2c70c1d0e33b370e13416f4450f645dddc4b2b5442b29593fa3914be0f09d5c97626cae1150ea81ecb661faaafe983a4c43e618764c762693520a6d

test:
  secret_key_base: acbf6d363f6dcd8f7407327154fc0aa54adab75ae1c603a511ebad8f9d3a7d9529186d7a97eb561cc66432bd410dd251378e6b6cbf6f86c6ac235c3652bb328b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
